### ISSUE TITLE
Damage Calculator

### ISSUE THREAD

**Issue by Varan** [hsahovic/poke-env#605]
I've heard there was some interest in connecting `poke-env` to the official damage calculator. 

I'd love to work on this, and was wondering if someone might be able to help point me in the right direction. Thanks!

**Comment by cameronangliss** [comment]
@caymansimpson would you say this is resolved?

**Comment by caymansimpson** [comment]
Yup! We still don't have reverse damage calculation and previous generations; but the damage calc implemented is akin to Gen9 Showdowns

**Comment by cameronangliss** [comment]
Great! Closing now.
